### ISSUE TITLE
Room list is incorrect immediately after joining

### ISSUE THREAD

**Issue by maxtros** [EionRobb/purple-discord#16]
After lastest commits Channels (roos) don't show participants on the room who joined before you join it/login...It only shows who joined after you joined.

Rev: Lastest .dll from today.

**Comment by maxtros** [comment]
Update: 

Also it seems people who joined after you...gets duplicate on the participants list

**Comment by EionRobb** [comment]
Managed to sort out the duplicates, but haven't been able to replicate the no-users problem yet

**Comment by EionRobb** [comment]
Aha, it wasn't adding people to the chat if the chat was already open (or open in the background) when reconnecting to the account.  That should fix it now, if you want to grab an updated dll :)

**Comment by maxtros** [comment]
Yeap those commit fix this issue (thanks eion) but now it has another bug...It seems that all rooms/channels has the same participants (only on participants list)

**Comment by Eloston** [comment]
Is checking the "Read Messages" permission sufficient to determine the subset of online users who are in the channel?

**Comment by alexolog** [comment]
I have joined a new channel and noticed two issues:
1. None of the participants were shown in the right pane except me
2. Messages from other participants were shown with their Discord name#id rather than the alias

So it seems that the bug is still there.

**Comment by bobbybee** [comment]
As a workaround, restarting Pidgin generally fixes this.

**Comment by bobbybee** [comment]
@EionRobb Occassionally the duplicates are still here. I don't understand what circumstances cause this to trigger.

**Comment by alexolog** [comment]
This happened to me several times:

1. My discord account is set with both checkboxes in the "advanced" tab cleared, and the "large channel" set to 20.
2. Launched Pidgin (Windows 10) with no discord conversations open
3. Somebody mentioned "@everyone" in a channel I registered on via the web interface and a Pidgin conversation window popped up.  All the members were triplicated.

See image:
http://img148.imagevenue.com/img.php?image=07592_Discord_122_203lo.jpg

**Comment by alexolog** [comment]
Holy crap.  I opened a chatroom tab and every person is duplicated 30-40 times.  This is ridiculous!

**Comment by bobbybee** [comment]
...I swear, it was Eion, not me :p

**Comment by alexolog** [comment]
Separation of responsibilities: Eion breaks, you fix

**Comment by alexolog** [comment]
Any luck?

**Comment by EionRobb** [comment]
I dug deep into uncharted enemy territory and found the source of the clone factory.

With carefully placed demolitions I managed to bury the code that caused the duplicated buddies.

Mission acomplished

**Comment by alexolog** [comment]
Great!  Does the Windows DLL have the fix?

**Comment by alexolog** [comment]
For some reason I don't see anything related to that in the commit history.

**Comment by EionRobb** [comment]
@alexolog the fix was in https://github.com/EionRobb/purple-discord/commit/21ac834ed1d2ca95cf05ecd57b542a4db7316d8a and yes the dll at https://eion.robbmob.com/libdiscord.dll has the change in it

**Comment by alexolog** [comment]
Oh sorry, the time of the announcement threw me off
