### ISSUE TITLE
Can't join 2 channels on 2 different servers with the same name at the same time.

### ISSUE THREAD

**Issue by tuxdude143** [EionRobb/purple-discord#39]
So I tried opening a channel called #general on two servers in pidgin but it seems that once one instance of said channel is open pidgin associates all channels with the same name as one in the same despite them being on different servers. Double clicking on a channel with the same name as an already joined channel on another server will not join the channel on the other server but will just bring the chat window to the front and display the channel with that name that was connected to first.

**Comment by EionRobb** [comment]
So recently we switched to using chat id's for uniqueness, but we still had some legacy code that would use the chat name as a fallback if the chat id didn't exist.

We'll just need to remove that legacy fallback code and this issue should be resolved :)

**Comment by Test1232311** [comment]
Greetings. The issue is still present. Are you going to fix it soon?

I don't know if this belongs here, but I highly appreciate you made Discord usable with FLOSS Software! This bug is the only major flaw
